### PR TITLE
Created pause and resume functionality

### LINKED ISSUE #118: User option to skip run numbers
This issue was originally [TRAC 11380](http://trac.mantidproject.org/mantid/ticket/11380)

This is different from 'http://trac.mantidproject.org/mantid/ticket/11378: Disable WebApp admin option'.

This is to allow users of a instrument to disable autoreduction for up and coming runs where it may e.g. never be relevant to run autoreduction, see Tatiana's comment below:

"Generally at the beginning of an experiment we run with white beam  (no fix incident energy) to align crystals and there will be a lot of run which does not make sense to reduce. This is an another reason for having the ability to start and stop the autoreduce when we decide to use it or not otherwise we will create a lot of files with errors."

 - - - - 
Keywords: AUTOREDUCTION

### PR DESCRIPTION
**Pull request by DominicOram**
Fixes #118

This adds the ability to pause an instrument causing any new runs submitted to be labelled as skipped.

To test WebApp GUI:
* On the 'All Jobs' page confirm that there is a pause/resume instrument link and that clicking it causes the link to change name.
* Resize the 'All Jobs' page to be mobile sized, confirm that the links become icons and operate as expected
* On an instrument summary page confirm that there is a pause/resume button and that pressing it causes expected behaviour

To test functionality:
* Pause an instrument
* Submit a job using a trigger script
* Refresh the 'All Jobs' screen and confirm that the run is shown as skipped and this is not counted as an error
* Resume the instrument and run a job again
* Confirm this run is processed as expected

### CODE REVIEW

**Comment by DominicOram** [comment]
Note that some unexpected behaviour can occur if multiple people attempt to pause/resume instruments. This will not update for others until the page is refreshed.

**Comment by Anders-Markvardsen** [comment]
First tested gui experience.

I can see the one-click benefit of having 'Pause' at the front of the 'All Jobs' page, but I am concerned there is already a lot of repeated text on this page, and I am struggling to warm to also having a 'Pause' column. See three images below. I was trying to think if 'Pause' could be placed somewhere else - smaller font / colour etc, but my recommendation is to remove the 'Pause' column from the 'All Jobs' page - but is happy to discuss this further.

autowithpausesmall-ish
autowithpausemedium
autowithpauselarge

I very much like the red button on:
autopauseoninstrument

But could the text be changed from 'Pause Instrument' to 'Pause Auto-reduction (for Merlin)' or 'Pause Auto-reduction (for this instrument)'. The reason why 'Pause Instrument' does not work is that an instrument scientists could read 'Pause Instrument' literally as: pause the actual instrument:-)

For the colouring of the button I would suggest having it the other way around, i.e. the button to be green when text is 'Pause...' and red when 'Resume...'. The red colour here is then to emphasis to the user that auto reduction is currently stopped for this instrument.

**Comment by DominicOram** [comment]
I agree that there is starting to be too much text on the 'All Jobs' page. However, from the description of Pascal's use case it sounds like something he would want to do as quickly as possible and as 'All Jobs' is our homepage it therefore makes sense to have it somewhere on there. Maybe we could replace the text with the mobile icons for all page sizes? We could place these icons in the far right hand side next to each instrument.

I agree with the changes to the instrument summary page, will make them now.

**Comment by DominicOram** [comment]
All suggested GUI changes have now been made

**Comment by Anders-Markvardsen** [comment]
Testing:

* Paused MERLIN
* Ran from tricker script an already reduced MERLIN run 25999. This created the log message on reduce:

{
[13/Aug/2015 16:20:50] INFO [django:67] Data ready for processing run 25999 on MERLIN
[13/Aug/2015 16:20:51] INFO [django:124] Run 25999 has been skipped
}

Entry added to WebApp 25999-1 with status Skipped

* ran MERLIN 25106, and run which had so far not been processed, which works as above hence as it should. Minor comment in webapp the name come out as 25106 - 1 where perhaps I would have expected just 25106.
* resumed MERLIN
* ran 25106 again

appeared in Webapp as 25106-2 with 'error' and hence tried to reduce this time

**Pull request merged**
