### PR TITLE
Save results to multiple directories

### LINKED ISSUE #210: Allow reduce.py to copy reduced files to multiple locations
To reproduce:

* Go to \\isis\inst$\NDXWISH\user\scripts\autoreduction
* edit reduce.py to have `output_folder` point to some folder the autoreduce can see but different from the ARCHIVE (in the case of WISH). 
* observe that no data are copied to this folder

### PR DESCRIPTION
**Pull request by Anders-Markvardsen**
Fixes #210 

To test:

* temporarily change the WISH reduce.py to save to a folder like `output_folder = '/ceph/instrument/WISH/CYCLE20151/RB1510257/testing/autoreduced/'`

* re-run a job for this RB number

observe that:

* just completes successfully
* clicking on the job multiple reduced output folders are specified
* reduced data have been saved successfully to disk

### CODE REVIEW

**Comment by DominicOram** [comment]
Works fine for one output directory but not for multiple. I attempted to do a run with the script as:   
'''
output_folder = ['/ceph/instrument/WISH/CYCLE20151/RB1510257/testing/autoreduced/','/ceph/instrument/WISH/CYCLE20151/RB1510257/testing/autoreduced2/']
'''

An error of "coercing to Unicode: need string or buffer, list found" was given

**Comment by Anders-Markvardsen** [comment]
@DominicOram could you try saving to a list again on production thanks

**Comment by DominicOram** [comment]
This still appears to be an issue (see http://reduce.isis.cclrc.ac.uk/runs/31317/15/)

**Comment by Anders-Markvardsen** [comment]
I forgot to update production server - please retest this now

**Comment by DominicOram** [comment]
Tested on re-run http://reduce.isis.cclrc.ac.uk/runs/31479/1/ 

Files appear in folders as expected.

**Pull request merged**
