### PR TITLE
Updated PostProcessAdmin.py

### LINKED ISSUE #132: Enable PostProcessAdmin to handle two reduction data storage location
This issue was originally [TRAC 11554](http://trac.mantidproject.org/mantid/ticket/11554)

Have all excitation instruments go to ceph and the rest somewhere else (probably for next cycle 'the archieve', i.e. on windows mounted as \\isis\inst$\blah...).

Out of ISIS cycle we may not be able to write to the archieve.

For this ticket chance PostProcessAdmin so that all excitation group reduced data go to one location and all other instrument reduced data to another location. 

For this ticket simply make this locations the same. 

 - - - - 
Keywords: AUTOREDUCTION

### PR DESCRIPTION
**Pull request by lottiegreenwood**
Fixes #132

### CODE REVIEW

**Comment by DominicOram** [comment]
**To test:** Send a reduction job for an excitation instrument, confirm that the reduced data is saved in CEPH. Send a reduction job for another instrument (WISH) and confirm reduced data is saved in archive.

**Comment by DominicOram** [comment]
The code for this is now on the production server, ready to be tested.

**Comment by Anders-Markvardsen** [comment]
Worked as it should when I ran tricker script with 30529 30529 111111 15_1, and the files appeared as they should in \\isis\inst$\NDXWISH\Instrument\data\cycle_15_1\autoreduced\111111\30529 .

However, when I rerun from the interface, the appeared to complete successfully, but there was then no output in \\isis\inst$\NDXWISH\Instrument\data\cycle_15_1\autoreduced\111111\30529

**Comment by DominicOram** [comment]
I believe the testing failure is slightly unrelated to this issue and is due to the same run being performed in quick succession. The separate processes trying to copy folders at similar times causes a lot of unexpected behaviour. I think this is sufficiently unrelated to deserve it's own issue. Therefore in testing this issue ensure that runs are sent a few minutes after previous runs on the same data have been completed.

**Comment by Anders-Markvardsen** [comment]
I now noticed the following.

Running the tricker script for WISH with 30532 30532 111111 15_1 then as before output is returned correctly to \\isis\inst$\NDXWISH\Instrument\data\cycle_15_1\autoreduced\111111\30532 . 
However just noticed that on the webapp:
```
Status: Completed
Instrument: WISH
RB Number: 111111
Last Updated: June 15, 2015, 7:30 a.m. 
Start: June 15, 2015, 7:29 a.m. 
Finish: June 15, 2015, 7:30 a.m. 
Duration: 45 seconds 
Data: \isis\NDXWISH\Instrument\data\cycle_15_1\WISH00030532.nxs
Reduced: ***No reduced data found***
```

**Comment by Anders-Markvardsen** [comment]
I accidentally closed this pull request - here reopen it

**Comment by Anders-Markvardsen** [comment]
issue referred to above will be dealt with separately

**Pull request merged**
